Repository atlassian/smith, pull requests merged in 2018-10, with the labels that each got.

#337 Dynamic /status subresource support detection
  pkg/controller/bundlec/bundle_sync_task.go
  pkg/controller/bundlec_test/BUILD.bazel
  pkg/controller/bundlec_test/zz_plumbing_for_test.go
Labels: enhancement

#342 add incoming edge functionality to dependency graph
  pkg/util/graph/topological_sort_test.go
  pkg/util/graph/types.go
Labels: enhancement

#341 Update RBAC definitions to allow events
  docs/deployment/1-common-rbac.yaml
  docs/deployment/1-service-account.yaml
  docs/deployment/2-cluster-wide-access-setup.yaml
  docs/deployment/2-namespaced-access-setup.yaml
Labels: Documentation, cleanup

#340 Propagate errors from Service Catalog back to the user
  pkg/controller/bundlec_test/BUILD.bazel
  pkg/controller/bundlec_test/propagate_status_test.go
  pkg/controller/bundlec_test/zz_objects_for_test.go
  pkg/readychecker/types/BUILD.bazel
  pkg/readychecker/types/built_in.go
  pkg/util/testing/utils_for_tests.go
Labels: bug

#346 Update dependencies to kube 1.12
  Gopkg.lock
  Gopkg.toml
  it/BUILD.bazel
  it/adoption_test.go
  it/resource_deletion_test.go
  it/update_test.go
  it/utils_for_tests.go
  pkg/apis/smith/v1/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/fake/BUILD.bazel
  pkg/client/clientset_generated/clientset/fake/register.go
  pkg/client/clientset_generated/clientset/scheme/BUILD.bazel
  pkg/client/clientset_generated/clientset/scheme/register.go
  pkg/client/clientset_generated/clientset/typed/smith/v1/bundle.go
  pkg/client/clientset_generated/clientset/typed/smith/v1/fake/fake_bundle.go
  pkg/controller/bundlec/resource_sync_task.go
  pkg/speccheck/BUILD.bazel
  pkg/speccheck/speccheck.go
Labels: enhancement

#347 Bump up tools versions
  .travis.yml
Labels: enhancement

#348 Update ctrl and use options from it
  Gopkg.lock
  Gopkg.toml
  examples/sleeper/main/BUILD.bazel
  examples/sleeper/main/main.go
  it/BUILD.bazel
  it/utils_for_tests.go
  pkg/client/BUILD.bazel
  pkg/client/config.go
Labels: cleanup

#351 Move diff logging into the resource sync task
  cmd/smith/app/bundle_controller.go
  pkg/controller/bundlec/resource_sync_task.go
  pkg/controller/bundlec/types.go
  pkg/speccheck/BUILD.bazel
  pkg/speccheck/speccheck.go
  pkg/speccheck/speccheck_test.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
Labels: cleanup

#352 Use assertion helper
  pkg/cleanup/types/BUILD.bazel
  pkg/cleanup/types/built_in.go
  pkg/readychecker/types/BUILD.bazel
  pkg/readychecker/types/built_in.go
Labels: cleanup

#355 Soft delete specification
  docs/design/soft-deletes.md
Labels: Documentation

#354 Documentation links
  README.md
Labels: Documentation

#353 Ensure integration tests are compilable
  Makefile
Labels: cleanup

#358 Clarify diff messages to aid debugging
  pkg/controller/bundlec/resource_sync_task.go
Labels: cleanup
