Repository atlassian/smith, pull requests merged in 2018-02, with the labels that each got.

#242 Remove blocked on error status
  pkg/apis/smith/v1/types.go
  pkg/controller/bundle_sync_task.go
  pkg/controller/controller_test.go
  pkg/controller/resource_sync_task.go
  pkg/util/util.go
Labels: enhancement

#243 Split controller_test
  pkg/controller/BUILD.bazel
  pkg/controller/controller_test.go
  pkg/controller/controller_worker.go
  pkg/controller/resource_sync_task.go
  pkg/controller_test/BUILD.bazel
  pkg/controller_test/actual_object_passed_to_plugin_test.go
  pkg/controller_test/cr_in_another_namespace_test.go
  pkg/controller_test/delete_removed_object_test.go
  pkg/controller_test/detect_infinite_update_cycles_test.go
  pkg/controller_test/invalid_depends_on_test.go
  pkg/controller_test/no_actions_for_blocked_resources_test.go
  pkg/controller_test/no_deletions_while_in_progress_test.go
  pkg/controller_test/plugin_schema_invalid_test.go
  pkg/controller_test/plugin_spec_processed_test.go
  pkg/controller_test/processing_continues_after_error_test.go
  pkg/controller_test/resolve_binding_secret_references_test.go
  pkg/controller_test/secret_keys_not_merged_test.go
  pkg/controller_test/two_resources_same_name_test.go
  pkg/controller_test/zz_plumbing_for_test.go
Labels: cleanup

#251 Add Meta field to Bundle output from //cmd/crd
  pkg/resources/crd_helpers.go
Labels: bug
