Repository atlassian/smith, pull requests merged in 2019-01, with the labels that each got.

#398 Build race binaries instead of pure ones by default
  cmd/crd/BUILD.bazel
  cmd/smith/BUILD.bazel
  examples/sleeper/main/BUILD.bazel
Labels: cleanup

#396 Initial support for soft delete
  api.go
  docs/design/soft-deletes.md
  pkg/controller/bundlec/bundle_sync_task.go
  pkg/controller/bundlec/resource_sync_task.go
  pkg/controller/bundlec_test/BUILD.bazel
  pkg/controller/bundlec_test/delay_postpone_delete_removed_object_test.go
  pkg/controller/bundlec_test/delay_proceed_delete_removed_object_test.go
  pkg/controller/bundlec_test/delay_start_delete_removed_object_test.go
  pkg/controller/bundlec_test/prohibited_annotations_object_test.go
  pkg/controller/bundlec_test/prohibited_annotations_plugin_test.go
  pkg/controller/bundlec_test/zz_plugins_for_test.go
  pkg/controller/bundlec_test/zz_plumbing_for_test.go
Labels: feature

#405 Update to kube 1.13 libs
  Gopkg.lock
  Gopkg.toml
  pkg/client/clientset_generated/clientset/typed/smith/v1/bundle.go
  pkg/client/clientset_generated/clientset/typed/smith/v1/fake/fake_bundle.go
  pkg/resources/BUILD.bazel
  pkg/resources/crd_helpers.go
Labels: enhancement

#406 Move Bundle CRD into a separate package
  cmd/crd/BUILD.bazel
  cmd/crd/main.go
  it/BUILD.bazel
  it/utils_for_tests.go
  pkg/controller/bundlec_test/BUILD.bazel
  pkg/controller/bundlec_test/zz_plumbing_for_test.go
  pkg/crd/BUILD.bazel
  pkg/crd/crd.go
  pkg/resources/BUILD.bazel
  pkg/resources/crd_helpers.go
Labels: cleanup

#409 Update bazel rules
  WORKSPACE
Labels: enhancement

#397 Enqueue Bundle on ConfigMap/Secret event
  cmd/smith/app/bundle_controller.go
  it/BUILD.bazel
  it/deployment_dependencies_test.go
  it/utils_for_tests.go
  pkg/controller/bundlec/BUILD.bazel
  pkg/controller/bundlec/controller.go
  pkg/specchecker/builtin/process_deployment.go
Labels: enhancement
